version: 2

sources:
  - name: nyc_fhvhv_tripdetails_zones_raw
    database: nyc-fhvhv
    schema: nyc_fhvhv_tripdetails_zones_raw

    tables: 
      - name: fhvhv_tripdata_2019-07
      - name: fhvhv_tripdata_2020-07
      - name: fhvhv_tripdata_2021-07
      - name: fhvhv_tripdata_2022-07
      - name: taxi_zone_lookup
      - name: JulyAllTripData

